description = 'mcp-client-plain'

dependencies {
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'
    implementation 'org.springframework.ai:spring-ai-starter-mcp-client'

    implementation 'org.zalando:logbook-spring-boot-starter'
    implementation 'org.zalando:logbook-okhttp'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
