spring:
  application:
    name: skill

  ai:
    openai:
      api-key: ${GEMINI_API_KEY:}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        model: gemini-3.1-flash-lite

agent.skills.path: classpath:/.agent/skills

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
    org.zalando: trace
