dependencies {
	implementation 'org.springaicommunity:spring-ai-starter-typesafe'
	implementation 'org.springaicommunity:typesafe-spring-ai'

	implementation 'org.zalando:logbook-spring-boot-starter'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
