description = '06-guardrails-builtin-structured-output'

dependencies {
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'

    implementation 'org.springaicommunity:spring-ai-inspector-starter'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
