spring:
  application:
    name: qdrant-semantic-cache

  ai:
    model:
      chat: openai
      embedding: google-genai
      embedding.text: google-genai

    openai:
      api-key: ${GEMINI_API_KEY:}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        model: gemini-3.1-flash-lite

    google:
      genai:
        embedding:
          api-key: ${GEMINI_API_KEY:}
          text:
            model: gemini-embedding-001
            task-type: semantic_similarity

    vectorstore:
      qdrant:
        initialize-schema: true

rag.document.url: classpath:Sagrada.pdf

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
    org.zalando: trace
    org.springframework.ai.vectorstore.redis.cache.semantic.DefaultSemanticCache: debug
