description = 'mcp-server'

dependencies {
    implementation 'org.springframework.ai:spring-ai-starter-mcp-server-webmvc'

    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springaicommunity:mcp-server-security-spring-boot'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
