description = 'auth-server'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-authorization-server'
    implementation 'org.springaicommunity:mcp-authorization-server'

    testImplementation 'org.springframework.boot:spring-boot-starter-security-oauth2-authorization-server-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
