spring:
  application:
    name: logging-googleai

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY:}
        chat:
          model: gemini-3.1-flash-lite

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
    org.zalando: trace