dependencies {
	implementation 'org.springframework.ai:spring-ai-starter-model-openai'
	implementation 'org.springframework.ai:spring-ai-redis-semantic-cache'
	implementation 'org.springframework.ai:spring-ai-starter-model-google-genai-embedding'
	implementation 'org.zalando:logbook-spring-boot-starter'
	implementation 'org.zalando:logbook-okhttp'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
