dependencies {
	implementation 'org.springframework.ai:spring-ai-starter-model-openai'

	implementation 'org.springframework.ai:spring-ai-starter-model-chat-memory-repository-jdbc'
	runtimeOnly 'org.postgresql:postgresql'

	implementation 'org.zalando:logbook-spring-boot-starter'
	implementation 'org.zalando:logbook-okhttp'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
