dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.ai:spring-ai-client-chat'

	implementation 'org.modeljars:modeljars'
	implementation 'com.integrallis:models-spring-ai'
	implementation 'org.modeljars.huggingface:qwen.qwen3-1.7b-gguf.q8_0'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('bootRun') {
	optimizedLaunch = false
	jvmArgs('--add-modules', 'jdk.incubator.vector')
}

tasks.named('test') {
	jvmArgs('--add-modules', 'jdk.incubator.vector')
}
