description = '03-modular-rag'

dependencies {
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'

    implementation 'org.springframework.ai:spring-ai-rag'
    implementation 'org.springframework.ai:spring-ai-pdf-document-reader'

    implementation 'org.springaicommunity:spring-ai-starter-typesafe'
    implementation 'org.springaicommunity:typesafe-spring-ai'

    implementation 'org.springaicommunity:spring-ai-inspector-starter'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
